---
title: "Project2"
author: "Matthew Hale"
date: "Tuesday, September 29, 2015"
output: html_document
---
Assignment
The basic goal of this assignment is to explore the NOAA Storm Database and answer some basic questions about severe weather events. You must use the database to answer the questions below and show the code for your entire analysis. Your analysis can consist of tables, figures, or other summaries. You may use any R package you want to support your analysis.
Questions: Your data analysis must address the following questions:
1.) Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?
2.) Across the United States, which types of events have the greatest economic consequences?
Consider writing your report as if it were to be read by a government or municipal manager who might be responsible for preparing for severe weather events and will need to prioritize resources for different types of events. However, there is no need to make any specific recommendations in your report.

```dataurl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"```  
```if (!exists("repdata-data-StormData.csv.bz2")){download.file(dataurl, "repdata-data-StormData.csv.bz2", method="curl")}```  
```data <- read.csv("repdata-data-StormData.csv.bz2")```  
```df <- select(data, "EVTYPE","FATALITIES","INJURIES","PROPDMG","PROPDMGEXP","CROPDMG","CROPDMGEXP")```  
```names(df) <- c("type", "fatal", "injuries', "prop", "propexp", "crop", "cropexp")```  
```df[grep("TORN", df$type),]$type <- "TORNADO"```  
```df[grep("HEAT", df$type),]$type <- "HEAT"```  
```df[grep("FLOOD", df$type),]$type <- "FLOOD"```  
```df[grep("SNOW", df$type),]$type <- "SNOW"```  
```df[grep("HURR", df$type),]$type <- "HURRICANE"```  
```df[grep("RAIN", df$type),]$type <- "RAIN"```  
```df[grep("HAIL", df$type),]$type <- "HAIL"```  
```df[grep("LIGHTNING", df$type),]$type <- "LIGHTNING"```  
```df[grep("THUNDER", df$type),]$type <- "THUNDER"```  
```df[grep("FUNNEL", df$type),]$type <- "TORNADO"```  
```df[grep("HOT", df$type),]$type <- "HEAT"```  
```df[grep("BLIZ", df$type),]$type <- "SNOW"```  
```df[grep("CHILL", df$type),]$type <- "COLD"```  
```df[grep("COLD", df$type),]$type <- "COLD"```  
```df[grep("FIRE", df$type),]$type <- "FIRE"```  








